[package]
name = "unit-pubsub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unit-utils = { path = "../utils" }
fred = { version = "7.0.0", features = ["subscriber-client"] }
