[package]
name = "unit-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
unit-utils = { path = "../utils" }
tokio = { version = "1.33.0", features = ["full"] }
clap = { version = "4.4.6", features = ["derive"] }
prost = "0.12.1"
tonic = "0.10.2"


[build-dependencies]
tonic-build = "0.10.2"
