[package]
name = "unit-index"
version = "0.1.0"
edition = "2021"

[dependencies]
unit-utils = { path = "../utils" }
unit-abi = { path = "../abi" }
serde = { version = "1.0.189", features = ["derive"] }
bincode = "1.3.3"

