version: "3.9"
services:
  redis:
    container_name: unit-redis
    image: redis:7-alpine
  api:
    container_name: unit-api
    image: laurci/unit:latest
    command: unit-api
    ports:
      - 6448:6448
    environment:
      - UNIT_REDIS_HOST=unit-redis
      - UNIT_REDIS_PORT=6379
      - UNIT_GRPC_API_KEY=ilovecats
  node:
    container_name: unit-node
    image: laurci/unit:latest
    command: unit-node
    ports:
      - 6447:6447
    environment:
      - UNIT_REDIS_HOST=unit-redis
      - UNIT_REDIS_PORT=6379
